language: python

python:
  - "3.7"
  - "3.8"

os:
  - linux

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE brokerweb;'

install:
  - pip install -r requirements.txt

script:
  - python manage.py test broker_web
