language: python

python:
  - '3.7'

os:
  - linux

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source='.' manage.py test broker_web
  - coverage report
  - mysql -e 'SHOW TABLES;'
