language: python

python:
  - '3.7'

os:
  - linux

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source='.' manage.py test broker_web

  # So that we can investigate failed migrations when building the test database
  - mysql -e 'use test_brokerweb; SHOW TABLES;'

  # So that we can read off test coverage from the travis build
  - coverage report
